# See: <https://rust-lang.github.io/rustfmt>

# rustfmt contains a number of options that aren't enforced by default (yet).
# We want to have a consistent style across the codebase, so we enable them here.
# Notably we don't want to customize any other settings, we just want to enable rules
# that are set to "preserve" by default.
unstable_features = true

blank_lines_upper_bound = 1
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
